definitions:
  http.UserRequest:
    properties:
      account:
        description: 帳號
        type: string
      password:
        description: 密碼
        type: string
    type: object
  http.UserRequestUpdateAccount:
    properties:
      new_account:
        description: 更新帳號
        type: string
    type: object
  http.UserRequestUpdatePassword:
    properties:
      new_password:
        description: 更新密碼
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: test-connect.
  title: test-connect-api
  version: 1.0.0
paths:
  /CRUD:
    get:
      consumes:
      - application/json
      description: 列出所有
      operationId: GetAllUser
      produces:
      - application/json
      responses:
        "200":
          description: Get All Users Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
      summary: GetAllUser
      tags:
      - CRUD
    post:
      consumes:
      - application/json
      description: 註冊
      operationId: Register
      parameters:
      - description: Register account
        in: body
        name: register_body
        required: true
        schema:
          $ref: '#/definitions/http.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Register Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: Register
      tags:
      - CRUD
  /CRUD/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除使用者
      operationId: DeleteUserByID
      parameters:
      - description: Delete Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Delete User Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
      summary: DeleteUserByID
      tags:
      - CRUD
    get:
      consumes:
      - application/json
      description: 列出欲查詢的使用者
      operationId: GetUser
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get User Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
      summary: GetUser
      tags:
      - CRUD
  /CRUD/login:
    post:
      consumes:
      - application/json
      description: 登入
      operationId: Login
      parameters:
      - description: Login account
        in: body
        name: login_body
        required: true
        schema:
          $ref: '#/definitions/http.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Register Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: Login
      tags:
      - CRUD
  /CRUD/uA/{id}:
    put:
      consumes:
      - application/json
      description: 更新使用者 Account
      operationId: Update Account By ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Account Struct
        in: body
        name: update_account
        required: true
        schema:
          $ref: '#/definitions/http.UserRequestUpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: Update User Successful
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: Update Account By ID
      tags:
      - CRUD
  /CRUD/uP/{id}:
    put:
      consumes:
      - application/json
      description: 更新使用者 Password
      operationId: Update Password By ID
      parameters:
      - description: Password ID
        in: path
        name: id
        required: true
        type: integer
      - description: Password Struct
        in: body
        name: update_password
        required: true
        schema:
          $ref: '#/definitions/http.UserRequestUpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: Update User Successful
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: Update Password By ID
      tags:
      - CRUD
  /TestConnect:
    post:
      consumes:
      - application/json
      description: 測試在 GCP Cloud Run 是否連得上不帶 pSQL 的映像檔
      operationId: Test Connect Cloud Run
      produces:
      - application/json
      responses:
        "200":
          description: Connect Cloud Run Successful
          schema:
            type: string
      security:
      - BearerOAuth2: []
      summary: Test Connect Cloud Run
      tags:
      - Test Connect
  /loginAzure/:
    post:
      consumes:
      - application/json
      description: 登入
      operationId: ToDisplayAccessToken
      produces:
      - application/json
      responses:
        "200":
          description: Get Access Token Successful
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
      summary: ToDisplayAccessToken
      tags:
      - login To Display Access Token
securityDefinitions:
  BearerOAuth2:
    authorizationUrl: ""
    flow: implicit
    type: oauth2
swagger: "2.0"
